Khan/wonder-stuff

- packages/wonder-stuff-core/package.json
- packages/wonder-stuff-core/src/__tests__/kind-error.test.js
- packages/wonder-stuff-core/src/kind-error.js
- packages/wonder-stuff-sentry/package.json
We don't want to normalize the message when we don't have a cause
as that would strip any useful information that the message might have
in that circumstance.
Issue: FEI-3998
`yarn test`
> [🔥AUDIT🔥] [fei3998.audit.1] Do not normalize message when there is no cause

- build-settings/rollup.config.js
- packages/wonder-stuff-core/README.md
- packages/wonder-stuff-core/package.json
- packages/wonder-stuff-core/src/__tests__/clone.test.js
- packages/wonder-stuff-core/src/__tests__/kind-error.test.js
- packages/wonder-stuff-core/src/__tests__/safe-stringify.test.js
- packages/wonder-stuff-core/src/clone-metadata.js
- packages/wonder-stuff-core/src/clone.js
- packages/wonder-stuff-core/src/index.js
- packages/wonder-stuff-core/src/kind-error.js
- packages/wonder-stuff-core/src/safe-stringify.js
- packages/wonder-stuff-core/src/types.js
- packages/wonder-stuff-sentry/README.md
- packages/wonder-stuff-sentry/package.json
- packages/wonder-stuff-sentry/src/__tests__/sentry-data-reducer.test.js
- packages/wonder-stuff-sentry/src/capture-error.js
- packages/wonder-stuff-sentry/src/collate-sentry-data.js
- packages/wonder-stuff-sentry/src/get-sentry-data-from-error.js
- packages/wonder-stuff-sentry/src/kind-sentry-error.js
- packages/wonder-stuff-sentry/src/types.js
- utils/pre-publish-check.js
This makes some tweaks to our Wonder Stuff APIs based on observations made when integrating it into webapp.
1. Fixes a bug in the `browser` property of package.json files so that the mapped paths are legitimate (updated build to properly assert this too)
1. Made composite stacks an optional feature (off by default).
1. Added return types for the sentry APIs to support common Sentry API definitions
1. Less read-only types so that callers don't have to work out how to make that work nicely
1. We export `clone` per an earlier review comment
1. Added `index.d.ts` to packages so that the JSDocs will show up for folks consuming our code (does not require TypeScript - this is a docs-only thing)
1. Updated test run script for packages so that folks can, to some degree, just run the tests they …
> [fei4142.1] A few fixes based on usage

- .github/workflows/node-ci.yml
- packages/wonder-stuff-sentry/src/__tests__/kind-error-data.test.js
- packages/wonder-stuff-sentry/src/__tests__/stringify-nested-contexts.test.js
- packages/wonder-stuff-sentry/src/default-kind-error-data-options.js
- packages/wonder-stuff-sentry/src/kind-error-data.js
- packages/wonder-stuff-sentry/src/stringify-nested-contexts.js
- packages/wonder-stuff-sentry/src/types.js
Sentry (at least on the plan we have) doesn't expand objects and arrays nested more than one level deep in contexts. This allows us to stringify these things so that they are still readable in the Sentry UX.
Issue: FEI-4142
`yarn test`
`yarn flow`
Integrate into webapp and demo it working.
> [fei4142.3] Add option to stringify nested context object and array values

- packages/wonder-stuff-testing/.babelrc.js
- packages/wonder-stuff-testing/README.md
- packages/wonder-stuff-testing/package.json
- packages/wonder-stuff-testing/src/index.js
- packages/wonder-stuff-testing/src/jest/__tests__/isolate-modules.test.js
- packages/wonder-stuff-testing/src/jest/isolate-modules.js
There are likely more things to go in this package moving forward, but for now, this helper
`yarn test`
> [wstesting] Add wonder-stuff-testing and isolateModules helper

- .github/workflows/node-ci.yml
So, we've dropped some of our special actions in favour of just calling package.json scripts.
Also, the coverage collection is no longer a parallel job but runs after linting/flow.
This will mean the branch protection rules need updating as I changed the name of a job.
See that #120 passes, please! Please?
> [🔥AUDIT🔥] [againandagain] Get things closer to what Wonder Blocks does and see if it works

- .eslintignore
- packages/wonder-stuff-testing/package.json
- packages/wonder-stuff-testing/src/errors.js
- packages/wonder-stuff-testing/src/index.js
- packages/wonder-stuff-testing/src/jest/__tests__/isolate-modules.test.js
- packages/wonder-stuff-testing/src/jest/__tests__/wait.test.js
- packages/wonder-stuff-testing/src/jest/index.js
- packages/wonder-stuff-testing/src/jest/internal/__tests__/assert-jest.test.js
- packages/wonder-stuff-testing/src/jest/internal/__tests__/unverified-wait.test.js
- packages/wonder-stuff-testing/src/jest/internal/__tests__/verify-real-timers.test.js
- packages/wonder-stuff-testing/src/jest/internal/assert-jest.js
- packages/wonder-stuff-testing/src/jest/internal/is-running-in-jest.js
- packages/wonder-stuff-testing/src/jest/internal/unverified-wait.js
- packages/wonder-stuff-testing/src/jest/internal/verify-real-timers.js
- packages/wonder-stuff-testing/src/jest/isolate-modules.js
- packages/wonder-stuff-testing/src/jest/wait.js
This copies the `wait.js` file from webapp so we can start sharing our implementation across projects, but refactors it to get better test coverage and clarity.
`yarn test`
> [wait] Add wait() to WS testing

- .github/workflows/node-ci-main.yml
- .github/workflows/node-ci.yml
This adds Node 16.x to the workflows and removes 14.x.
We will then want to make sure we target the lerna build to the correct version (which would be the version installed locally - currently 12.x).
Issue: FEI-4349
See what happens when GitHub runs the workflows.
> [fei4349.1.addtestsfornode16] Add 16.x to workflow matrices

- .github/workflows/release.yml
We want our other workflows to trigger when the Version Packages PR is created. This updates the release workflow that creates that PR to use a personal access token with repo scope instead of the GITHUB_TOKEN so that it will do just that.
I've added a comment in the workflow for folks in case something happens to me or the token expires (currently set to expire after 90 days). That way folks know how to make a new token.
Issue: FEI-4220
Land this on `main` and see what happens... :fingers_crossed:
> [🔥AUDIT🔥] [fixreleaseactiontriggers] Use personal access token for release workflow

- .github/workflows/release.yml
The force push of the changeset action doesn't retrigger workflows, which is anoying since the use of the personal access token has fixed the PR creation part. I added the SSH agent to try and address this but it still didn't work, so seeing if cloning the repo directly instead of using the checkout action will fix that.
Issue: FEI-4220
Land on `main` and see what happens.
> [🔥AUDIT🔥] [trycloning] Try cloning the repo instead of checkout action

- .changeset/warm-terms-care.md
- packages/wonder-stuff-core/src/__tests__/values.flowtest.js
- packages/wonder-stuff-core/src/__tests__/values.test.js
- packages/wonder-stuff-core/src/index.js
- packages/wonder-stuff-core/src/values.js
This adds a version of `values()` that provides strong typing of the returned array, rather than `Array<mixed>` as `Object.values()` would.
Issue: FEI-4636
`yarn test`
`yarn flow`
> [fei4636.1] Add values() method

- .changeset/jeff-wrote-this.md
- packages/wonder-stuff-core/src/__tests__/keys.flowtest.js
- packages/wonder-stuff-core/src/__tests__/keys.test.js
- packages/wonder-stuff-core/src/index.js
- packages/wonder-stuff-core/src/keys.js
This adds an wrapper around `Object.keys` that returns `Array<$Keys<O>>` instead of `Array<string>`.
Issue: FEI-4636
`yarn test`
`yarn flow`
> [fei4636.2] Add keys() method

- .changeset/and-this-too.md
- packages/wonder-stuff-core/src/__tests__/entries.flowtest.js
- packages/wonder-stuff-core/src/__tests__/entries.test.js
- packages/wonder-stuff-core/src/entries.js
- packages/wonder-stuff-core/src/index.js
This adds a strongly typed `entries()` method to use in place of `Object.entries()`
Issue: FEI-4636
`yarn test`
`yarn flow`
> [fei4636.3] Add entries() method

- yarn.lock
I think a little script for handling this would be great so that we don't forget to run `yarn` after the dedupe (which I remembered this time) and make sure to commit at that point (which I forgot this time).
Perhaps a GitHub action CRON job might be in order so we can easily do this across our repos (until we move off yarn v1).
`yarn`
`npx yarn-deduplicate yarn.lock`
Repeat until no changes are made.
`yarn test`
`yarn flow`
> [🔥AUDIT🔥] [dedupe.2] Forgot to commit the yarn.lock changes after running yarn :facepalm:

- .changeset/sharp-houses-sip.md
- flow-typed/ka-types.js
- packages/wonder-stuff-testing/src/__tests__/data-factory-for.test.js
- packages/wonder-stuff-testing/src/data-factory-for.js
- packages/wonder-stuff-testing/src/index.js
This PR extracts 'getCreateMockData' from https://github.com/Khan/webapp/pull/8976 so that we can use it other repo than just 'webapp'.  This PR also:
- renames this function to 'dataFactoryFor'
- updates the examples in the documentation so that they show valid usage
- fixes a bug in the code that could've resulting in mutation of the partial object being passed to the data factory
Issue: None
- yarn test
> Add 'dataFactoryFor' function to help generate mock data

- .changeset/weak-dolls-reflect.md
- packages/wonder-stuff-core/src/__tests__/errors-from-error.test.js
- packages/wonder-stuff-core/src/kind-error.js
- packages/wonder-stuff-i18n/src/plugins/__tests__/i18n-plugin.test.js
- packages/wonder-stuff-i18n/src/plugins/i18n-plugin.js
- packages/wonder-stuff-i18n/src/utils/__tests__/localize-file.test.js
- packages/wonder-stuff-i18n/src/utils/extract-i18n.js
- packages/wonder-stuff-testing/src/jest/isolate-modules.js
> Correct flow types for isolateModules

- .changeset/long-pears-laugh.md
- config/jest/test.config.js
- packages/eslint-config-khan/index.js
- packages/wonder-stuff-core/src/__tests__/entries.test.ts
- packages/wonder-stuff-core/src/__tests__/entries.typestest.ts
- packages/wonder-stuff-core/src/__tests__/keys.test.ts
- packages/wonder-stuff-core/src/__tests__/keys.typestest.ts
- packages/wonder-stuff-core/src/__tests__/values.test.ts
- packages/wonder-stuff-core/src/__tests__/values.typestest.ts
- packages/wonder-stuff-core/src/entries.ts
- packages/wonder-stuff-core/src/keys.ts
- packages/wonder-stuff-core/src/values.ts
- yarn.lock
I did some more thinking about this and updating all of our uses of these wrappers in webapp is going to be a pain. It'll be easier to drop the wrappers after the conversion. I was able to add types for the overloads that TypeScript provides. It'll be interesting to see how well these translate to Flow.  I've also update the eslint config to ignore variables that are just underscores which is what we had originally.
Issue: FEI-4957
- yarn lint
- yarn build:types
- yarn build:flowtypes
- copy/paste the types for entries, keys, and values into the Flow playground and do some spot check testing with them (it's okay if their behavior isn't exactly the same as the old Flow types for these wrappers)
> FEI-4957.10: Re-add entries, keys, and values wrappers

- .changeset/long-hairs-turn.md
- .eslintrc.js
- packages/eslint-config-khan/README.md
- packages/eslint-config-khan/index.js
- packages/eslint-config-khan/package.json
When I initially updating the eslint config to support TypeScript, I added settings to .eslintrc.js that I should've added to eslint-config-khan/index.js.  Without these settings, using @khanacademy/eslint-config in other codebases would fail.
TODO:
Issue: FEI-4957
- add some lint
- see that it's reported in VSCode
- yarn lint, see that it's reported
- fix the lint
- yarn lint, see there's no lint
> FEI-4957.11: Reorganize eslint configs

- .changeset/beige-otters-exist.md
- packages/wonder-stuff-server/package.json
When reviewing the changes in #536, I noticed that some packages were being bumped a major version even though none of the changeset .md files specified such changes.  It appears this is happening due changeset treating peer deps differently from regular deps.  This PR fixes the issue by make wonder-stuff-core a regular dependency of wonder-stuff-server.
Issue: None
- land this PR and see #536 update appropriately
> Make core a real dep of server

- .changeset/dull-fishes-relate.md
- packages/wonder-stuff-server-google/package.json
- packages/wonder-stuff-testing/package.json
I updated wonder-stuff-server's deps in #544, but missing that wonder-stuff-testing and wonder-stuff-server-google are affected by the same issue.  This PR fixes them as well.
Issue: None
- Land and wait for #536, see that wonder-stuff-server-google and wonder-stuff-testing are bumped by a minor version
> Convert more peer deps into real deps

- .changeset/quick-keys-learn.md
- build-scripts/gen-flow-types.ts
Some of the files flowgen was generated were using 'mixins' instead of 'extends'. This PR fixes this by post-processing the files.
Issue: None
- yarn build:types
- yarn build:flowtypes
- search for 'mixins' in the dist/ folders, see that it no longer appears there
> Remove 'mixins' from .js.flow output

- .changeset/selfish-candles-call.md
- packages/wonder-stuff-server-google/src/trace-impl.ts
- packages/wonder-stuff-server-google/src/types.ts
For some reason the 'get' modifier on the 'action()' getter in ITRaceSession was dropped when the files were converted to TypeScript.  I checked the other getters we have, which are on classes, but they weren't affected.  I suspect it's an issue with the codemod.  I'll investigate later and will patch is possible.
Issue: None
- yarn typecheck
> Fix issues with action() not being a getter on ITraceSession

- .changeset/old-plants-exist.md
- .npmpackagejsonlintrc.json
- package.json
- packages/wonder-stuff-core/package.json
- packages/wonder-stuff-i18n/package.json
- packages/wonder-stuff-sentry/package.json
- packages/wonder-stuff-server-google/package.json
- packages/wonder-stuff-server/package.json
- packages/wonder-stuff-testing/package.json
- utils/pre-publish-check-ci.js
- utils/pre-publish-utils.js
- yarn.lock
This PR introduces a tool for linting our package.json files.  It's configured to require 'types' along with existing fields such as 'main' and 'module'.  This PR replaces the 'source' field with the 'types' field.  Eventually we'll configure files properly so we aren't shipping any source code at all, but I'm going to leave that for another day.
Issue: None
- yarn lint:pkg-json
> Add 'types' field to wonder-stuff package.json files

- .changeset/wise-trains-deny.md
- build-settings/rollup.config.js
One of our cloud platform jobs is failing because dist/bin/gen-potfiles.ts was written instead of dist/bin/gen-profiles.js when wonder-stuff-i18n was built and published.  This PR fixes the issue by updating the build script to write bin files using hte .js extension instead of .ts.
Issue: None
- ./packages/wonder-stuff-i18n/dist/bin/gen-potfile.js "../webapp/services/static/javascript/*.{js,jsx}" > JavaScript.pot
- cat JavaScript.pot
- see a bunch of strings ready for translations
> Fix wonder-stuff-i18n's dist/bin/ folder

- .changeset/shy-pillows-hear.md
- build-settings/rollup.config.js
- package.json
- yarn.lock
While working on the render-gateway migration and dealing with a yarn.lock conflict, I noticed that the terser plugin we are using with rollup was deprecated. This updates us to the current version.
`yarn build`
> Update from deprecated terser plugin to maintained version

- packages/wonder-stuff-server/src/middleware/__tests__/request-authentication.test.ts
- packages/wonder-stuff-server/src/middleware/request-authentication.ts
- packages/wonder-stuff-server/src/middleware/wrap-with-middleware.ts
- packages/wonder-stuff-server/src/types.ts
This makes the request authentication options optional as it used to be in the original implementation. This makes writing tests and example uses easier.
Issue: FEI-4960
`yarn test`
`yarn typecheck`
> [🔥AUDIT🔥] [fei4960.optionalauthentication] Make auth options optional again

- .changeset/beige-dragons-kiss.md
- .changeset/fast-frogs-shake.md
- .github/workflows/node-ci.yml
- build-settings/rollup.config.js
- packages/wonder-stuff-core/package.json
- packages/wonder-stuff-sentry/package.json
- packages/wonder-stuff-testing/package.json
- utils/pre-publish-utils.js
This builds on the rollup config changes from the previous PR, making them more transparent and understandable, as well as making sure that it works for the browser builds, should they need it.
I bumped some package versions since this modifies the entrypoint paths for the browser builds.
Issue: FEI-4960
`yarn build` and check the output.
> [fei4960.3.rollup] Support dynamic import for all build types

- .changeset/stupid-beds-walk.md
- packages/wonder-stuff-core/src/__tests__/keys.typestest.ts
- packages/wonder-stuff-core/src/keys.ts
This updates the typing of the `keys` function to match better with our expected usage.
Issue: FEI-4960
`yarn typecheck`
Also built the types and tried them in webapp to verify they now work as we would want.
> [🔥AUDIT🔥] [rg.audit.3] Fix keys typing

- .changeset/khaki-files-punch.md
- packages/eslint-plugin-khan/README.md
- packages/eslint-plugin-khan/lib/rules/sync-tag.js
- packages/eslint-plugin-khan/package.json
- packages/eslint-plugin-khan/test/sync-tag_test.js
- yarn.lock
I forgot to 'git pull' in my local checkout of eslint-plugin-khan so the code I had locally was out of date.
I copied sync-tag.js and sync-tag_test.js wholesale from Khan/esling-plugin-khan@master and then ported the rest by hand using https://github.com/Khan/eslint-plugin-khan/compare/eedc8fe1794ef5fedc6d49578891854ac8193d75...master as a reference.
Issue: None
- yarn --cwd packages/eslint-plugin-khan test
> Port checksync changes form eslint-plugin-khan

- .changeset/calm-schools-tease.md
- packages/eslint-plugin-khan/.eslintrc.js
- packages/eslint-plugin-khan/lib/rules/imports-requiring-flow.js
- packages/eslint-plugin-khan/test/flow-array-type-style_test.js
- packages/eslint-plugin-khan/test/imports-requiring-flow_test.js
- packages/eslint-plugin-khan/test/sync-tag_test.js
The console.logs make the CI logs really noisy and they don't need to be there.
Issue: None
- yarn --cwd packages/eslint-plugin-khan test
> Remove logging from eslint-plugin-khan

- .changeset/long-houses-hear.md
- .eslintrc.js
- packages/eslint-config-khan/index.js
By moving these rules into the eslint-config-khan package, we can more easily adopt them in other repos.  In particular, if a repo is using dependabot then these new rules should be added automatically.
Issue: None
- publish, see if dependenbot creates a PR in wonder-blocks with this change
> Move TS enum eslint rules into config package

- .changeset/eighty-lobsters-flash.md
- packages/wonder-stuff-core/src/__tests__/type-predicates.test.ts
- packages/wonder-stuff-core/src/__tests__/type-predicates.typestest.ts
- packages/wonder-stuff-core/src/index.ts
- packages/wonder-stuff-core/src/type-predicates.js.flow
- packages/wonder-stuff-core/src/type-predicates.ts
.filter(Boolean) doesn't work in TS like it does in Flow. To address this issue, I'm adding a couple of type predicates to wonder-stuff-core.  I'll be updating webapp to use these predicates before the migration.  I'll also be creating a fixable eslint rule for this so that people trying to use '.filter(Boolean)' after the migration can easily move to the new pattern.
Issue: FEI-5141
TODO:
- yarn tsc
- yarn test type-predicates
- yarn build:docs
- open docs/index.html
- see the beautiful docs
> FEI-5141.1: Add isTruthy and isNonNullable type predicates to wonder-stuff-core

- .changeset/sweet-apes-decide.md
- packages/wonder-stuff-core/src/__tests__/unreachable-case-error.test.ts
- packages/wonder-stuff-core/src/__tests__/unreachable-case-error.typestest.ts
- packages/wonder-stuff-core/src/index.ts
- packages/wonder-stuff-core/src/unreachable-case-error.ts
In webapp and mobile we have some exhaustive switch-case statements using `(value: empty)` in the `default` case so that Flow can ensure that we've handled all of the possible cases.  TS doesn't have the same kind of type assertions so we'll use `UnreachableCaseError` instead.  The constructor for this error class takes a parameter that is unassignable (it's typed as `never`).  This means if we don't handle all of the cases, TS will complain because the `default` case will be reachable now.  This same approach will work with Flow as will.  Once I've published wonder-stuff-core, I'll update webapp to make use of it.  The mobile repo has already been migrated to TS, but can still make use of this new error class.
Issue: FEI-5142
- `yarn test unreachable-case-error`
- `yarn build:docs`
- …
> FEI-5142: Add UnreachableCaseError for use in exhaustive switch-case statements

- .changeset/grumpy-hats-dress.md
- .gitignore
- packages/eslint-plugin-khan/docs/ts-no-error-suppressions.md
- packages/eslint-plugin-khan/src/rules/array-type-style.ts
- packages/eslint-plugin-khan/src/rules/jest-async-use-real-timers.ts
- packages/eslint-plugin-khan/src/rules/jest-await-async-matchers.ts
- packages/eslint-plugin-khan/src/rules/no-one-tuple.ts
- packages/eslint-plugin-khan/src/rules/react-no-method-jsx-attribute.ts
- packages/eslint-plugin-khan/src/rules/react-no-subscriptions-before-mount.ts
- packages/eslint-plugin-khan/src/rules/react-svg-path-precision.ts
- packages/eslint-plugin-khan/src/rules/ts-no-error-suppressions.ts
- packages/eslint-plugin-khan/test/rules/array-type-style.test.ts
- packages/eslint-plugin-khan/test/rules/no-one-tuple.test.ts
We use "error", "warn", or "off" to control whether a rule runs or not.  The "always"/"never" option doesn't really make sense for the rules we currently have so I've removed those options from all of our eslint rules in this PR.
- yarn test eslint-plugin
> Tweak eslint rule options to not use "always"/"never"

- .changeset/good-months-change.md
- packages/eslint-config-khan/index.js
- packages/eslint-config-khan/package.json
The ts-no-error-suppressions error should be used in all of our repos with React code that have been converted to TypeScript. This PR updates our eslint config to include this rule.
Issue: None
- yarn build
- reload the eslint plugin in VSCode
- see that VSCode is no longer complaining about it not being able to find the rule
- node utils/pre-publish-check-ci.js  
NOTE: Khan/actions@check-for-changet will fail until https://github.com/Khan/actions/pull/44 is landed.
> Update eslint-config-khan to include @khanacademy/ts-no-error-suppressions

- .changeset/ten-ladybugs-develop.md
- packages/wonder-stuff-ci/package.json
This ensures that we don't try to inline the logging-winston code, which incorrectly excludes some of the code
`yarn build` and check that `./common` is not in the index.js for wonder-stuff-ci.
We'll also test this in @jlauzy's work where this issue was identified.
> [fixwscibuild] Make sure peer dependencies are added for wonder-stuff-ci

- .changeset/tricky-pillows-sin.md
- packages/wonder-stuff-ci/package.json
- packages/wonder-stuff-ci/src/__tests__/get-gcp-log-transport.test.ts
- packages/wonder-stuff-ci/src/__tests__/get-mobile-release-logger.test.ts
- packages/wonder-stuff-ci/src/get-gcp-log-transport.ts
- packages/wonder-stuff-ci/src/get-mobile-release-logger.ts
- packages/wonder-stuff-ci/src/types.ts
- The logger no longer works because GCP's API made a breaking change where the resource type is required.
- Cleaned up the code to have more flexibility for these changes by exposing more configuration to the client.
I'm pretty sure they are going to make a change to their SDK so that this is no longer nullable but required
Works Again!
> Cleaned up the code and fix the logger for new required type by GCP API

- .changeset/six-glasses-flow.md
- packages/wonder-stuff-core/src/index.ts
- packages/wonder-stuff-core/src/type-predicates.js.flow
For some reason 'export * from ...' doesn't work.
Issue: None
- yarn build
- check the dist/index.js for wonder-stuff-core to see that 'isTruthy' and 'isNonNullable' both appear in the output
> Fix exports of isTruthy and isNonNullable

- .changeset/kind-balloons-move.md
- .eslintignore
- config/jest/test.config.js
- packages/eslint-plugin-khan/.mocharc.js
- packages/eslint-plugin-khan/package.json
- packages/eslint-plugin-khan/src/react-utils.js
- packages/eslint-plugin-khan/src/rules/flow-array-type-style.js
- packages/eslint-plugin-khan/src/rules/flow-exact-props.js
- packages/eslint-plugin-khan/src/rules/flow-exact-state.js
- packages/eslint-plugin-khan/src/rules/flow-no-one-tuple.js
- packages/eslint-plugin-khan/src/rules/imports-requiring-flow.js
- packages/eslint-plugin-khan/src/rules/index.ts
- packages/eslint-plugin-khan/src/rules/jest-enzyme-matchers.js
- packages/eslint-plugin-khan/test/rules/flow-array-type-style.test.js
- packages/eslint-plugin-khan/test/rules/flow-exact-props.test.js
- packages/eslint-plugin-khan/test/rules/flow-exact-state.test.js
- packages/eslint-plugin-khan/test/rules/flow-no-one-tuple.test.js
- packages/eslint-plugin-khan/test/rules/jest-enzyme-matchers.test.js
- tsconfig-common.json
- yarn.lock
We want to be able to run eslint both before and after migration without having to change the version of eslint itself.  This will simplify the migration, but it means we need those old eslint rules that I deleted back in #692.  This PR adds them back.
I needed to tweak the mocha configuration to process the files with 'swc' so that it can load src/index.ts.
Issue: None
- cd packages/eslint-config-khan
- yarn install
- yarn test
> Re-add old eslint rules

- .changeset/tough-trainers-complain.md
- packages/eslint-plugin-khan/src/rules/imports-requiring-flow.js
- packages/eslint-plugin-khan/src/rules/index.ts
- packages/eslint-plugin-khan/test/rules/imports-requiring-flow.test.js
I accidently missed exporting this rule after re-adding the code for 'imports-requiring-flow'.  This PR re-adds it and re-adds the associate unit tests as well.
Issue: None
- cd packages/eslint-plugin-khan
- yarn test
> Export 'imports-requiring-flow' eslint rule

- .changeset/silver-experts-attend.md
- .changeset/young-cameras-fail.md
- build-settings/CHANGELOG.md
- build-settings/package.json
- packages/wonder-stuff-ci/CHANGELOG.md
- packages/wonder-stuff-ci/package.json
- packages/wonder-stuff-core/package.json
- packages/wonder-stuff-i18n/package.json
- packages/wonder-stuff-render-environment-jsdom/CHANGELOG.md
- packages/wonder-stuff-render-environment-jsdom/package.json
- packages/wonder-stuff-render-server/CHANGELOG.md
- packages/wonder-stuff-render-server/package.json
- packages/wonder-stuff-sentry/package.json
- packages/wonder-stuff-server/CHANGELOG.md
- packages/wonder-stuff-server/package.json
- packages/wonder-stuff-testing/package.json
Revert "Version Packages (#853)"
The deploy script is trying to run 'yarn build:flowtypes' which no longer exists.  I'll fix that in a separate PR.
Issue: None
- n/a, it's a clean revert
> [🔥AUDIT🔥] <Replace this with your pull request title>

- .changeset/chatty-cobras-roll.md
- packages/wonder-stuff-testing/src/jest/wait.ts
The `wait` function copied from Webapp verified that jest was in use at import. This worked when in webapp and it was just a file being imported, but now it's in Wonder Stuff Testing, it causes an error if any of the non-jest code is used outside of a jest environment, which is not what we want at all.
So, this removes that module level check, which in turn means Wonder Stuff Testing can be used in non-jest contexts, like stories.
See [Slack thread](https://khanacademy.slack.com/archives/CEA6W0F6F/p1707955461083099?thread_ts=1707867450.595019&cid=CEA6W0F6F) for more context, if you have access.
`yarn test`
Once published, we can update webapp and verify `dataFactoryFor` is usable within stories.
> [fixusageoutsidejest] Allow import outside of jest

- .changeset/six-chefs-doubt.md
- .npmignore
This adds an `.npmignore` file to the project to exclude unnecessary files from the published package. Any `files` declaration in a `package.json` will override this, so that's something to watch out for, but this is sufficient for now.
Issue: FEI-5815
1. `yarn`
2. `yarn build`
3. `yarn build:types`
4. `rm .npmignore`
5. `cd packages/wonder-stuff-server`
6. `npm pack --dry-run`
7. Observe that the `tsconfig-build.json` and `tsconfig-build.tsbuildinfo` are included
8. `cd ../..`
9. `git checkout .npmignore`
10. `cd packages/wonder-stuff-server`
11. `npm pack --dry-run`
12. Observe that the `tsconfig-build.json` and `tsconfig-build.tsbuildinfo` are not included
> [fei5815.1.excludebuildinfo] Add .npmignore file

- .changeset/brave-scissors-repair.md
- .changeset/dirty-islands-bake.md
- .eslintignore
- lint_ignore.txt
- package.json
- packages/eslint-config-khan/package.json
- packages/eslint-plugin-khan/README.md
- packages/eslint-plugin-khan/demo/.eslintrc.js
- packages/eslint-plugin-khan/demo/package.json
- packages/eslint-plugin-khan/demo/src/foo.tsx
- packages/eslint-plugin-khan/demo/yarn.lock
- packages/eslint-plugin-khan/docs/aphrodite-add-style-variable-name.md
- packages/eslint-plugin-khan/package.json
- packages/eslint-plugin-khan/src/rules/aphrodite-add-style-variable-name.ts
- packages/eslint-plugin-khan/src/rules/index.ts
- packages/eslint-plugin-khan/test/rules/aphrodite-add-style-variable-name.test.ts
- yarn.lock
Adding a custom lint rule to ensure consistent naming for when we use `addStyle` for aphrodite styling. Variable naming should be in the format `StyledTag`.
By having predictable names for styled elements, we are able to use [component mapping](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y?tab=readme-ov-file#component-mapping) more effectively for `eslint-plugin-jsx-a11y` so it can use the underlying HTML for accessibility checks. 
Issue: FEI-5952
Related ADR: [ADR-781](https://khanacademy.atlassian.net/wiki/x/IoBVyg)
- Tests pass
- Linting works in the demo project (will need some help with this!)
[ADR-781]: https://khanacademy.atlassian.net/browse/ADR-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add aphrodite-add-style-variable-name lint rule

- .changeset/perfect-cycles-fry.md
- packages/eslint-plugin-khan/src/rules/aphrodite-add-style-variable-name.ts
- packages/eslint-plugin-khan/test/rules/aphrodite-add-style-variable-name.test.ts
Updating the error message so it is more useful (noticed this after testing with the demo project)
Previously: `Variable name "div" does not match tag name "div". Variable name should be "StyledDiv"`
New: `Variable name "div" does not match the expected naming convention. Expected: "StyledDiv"` 
Issue: FEI-5952
- Tests continue to pass
- Will integrate with the demo project once this update is released!
> Update error message for aphrodite-add-style-variable-name rule

- .changeset/happy-dots-bake.md
- packages/eslint-plugin-khan/demo/package.json
The most recent release failed near the end because it tried to publish the `demo` project. This PR changes the demo project to be explicitly private. This will help changesets know not to try to publish it. 
This didn't happen in the demo project in earlier releases because it wasn't in the Yarn workspace. With pnpm, we can add it to the workspace, but that caused changesets to try to publish it.  By marking it as `private: true`, we'll block that in the future. 
Issue: FEI-6300
We'll need to land this and then release the Version Packages PR that's created by it.
> Mark demo project as non-publishable
